### ISSUE TITLE
List of things. 9 bullets to fix

### ISSUE THREAD

**Issue by RolfS02** [shoppingio/community-feedback#5]
1. When you register it does not show your SPIO-amount. Only the SPI-amount in your wallet. And .club stakers don't get the discount. (At least on the current version)

2. Text on newsroom and https://beta.shopping.io/ecosystem is still Lorem Ipsen in the top and a referred hyperlink just beneath is missing

3. No description of the plans yet anywhere. Intentional maybe. 

4. The "Explore" buttons on the frontpage is missing hyperlinks

5. Describing text at the "roadmap section" does not have anything to do with the roadmap. Maybe intential as well: 

"Roadmap - 
SPI makes it possible to use over 100 different cryptocurrencies to purchase items on eccomerce platforms like Amazon US, UK, CA, DE, Walmart, Ebay, Etsy and more! For the first time, spending your crypto is as easy as the click of a button."

6. Choosing DE, CA, US or UK looks a bit like a language setting. But it looks smooth. 

7. A darktheme for the homepage would be amazing as well.

8. Pagespeed when loading a product is to the slow side - like 5 seconds. Not sure what to do about though. The API is working at limited speed I guess.

9. You can't remove items from the cart

10. If you cancel an order in Utrust it will still appear on the frontpage as "pending".

**Comment by kwehmatthew** [comment]
> 2. Text on newsroom and https://beta.shopping.io/ecosystem is still Lorem Ipsen in the top and a referred hyperlink just beneath is missing

This has been resolved.

**Comment by softstack** [comment]
1. When you register it does not show your SPIO-amount. Only the SPI-amount in your wallet. And .club stakers don't get the discount. (At least on the current version) @kwehmatthew 
Question: SPIO staker shall get the same discount as SPI holder ?

_2. Text on newsroom and https://beta.shopping.io/ecosystem is still Lorem Ipsen in the top and a referred hyperlink just beneath is missing
**Fixed**_

_3. No description of the plans yet anywhere. Intentional maybe. 
**Fixed**_

_4. The "Explore" buttons on the frontpage is missing hyperlinks
**Fixed**_

_5. Describing text at the "roadmap section" does not have anything to do with the roadmap. Maybe intential as well: 
_no bug__

_6. Choosing DE, CA, US or UK looks a bit like a language setting. But it looks smooth. 
**no bug**_

_7. A darktheme for the homepage would be amazing as well.
**no bug**_

**Open:** 
8. Pagespeed when loading a product is to the slow side - like 5 seconds. Not sure what to do about though. The API is working at limited speed I guess.

9. You can't remove items from the cart

10. If you cancel an order in Utrust it will still appear on the frontpage as "pending".

**Comment by softstack** [comment]
Closed:
9. You can't remove items from the cart

Open:
8. Pagespeed when loading a product is to the slow side - like 5 seconds. Not sure what to do about though. The API is working at limited speed I guess.

10. If you cancel an order in Utrust it will still appear on the frontpage as "pending".
